version: "3"

services:
  # PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: app
    container_name: app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./laravel-app:/var/www/html
    networks:
      - laravel
    depends_on:
      - db

  # Nginx Service
  web:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./laravel-app:/var/www/html
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - "80:80"
      - "443:443"
    networks:
      - laravel
    depends_on:
      - app

  # MySQL Service
  db:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    # env_file:
    #   - mysql.env
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  mysql-data:
    driver: local
